### ISSUE TITLE
Const variables not visible

### ISSUE THREAD

**Issue by ardicDemirol** [dogugzm/Unity-PlayerPrefs-Tool#1]
The tool cannot detect my immutable variables when using a const variable instead of the classic string. I tried a lot but couldn't solve the problem. Here is an example that causes this problem.

--------------------------------------------------------------------------------

private const string MUSIC_VOLUME = "MusicVolume";
PlayerPrefs.SetFloat(MUSIC_VOLUME, volume);

**Comment by dogugzm** [comment]
Thanks for the feedback. Working on this...

**Comment by dogugzm** [comment]
@ardicDemirol I fixed and tested for const and non-const variables. I hope it helps.

**Comment by ardicDemirol** [comment]
> Thanks for the feedback. Working on this...

Working , Thank you bro
